# site settings
title: Kyle Fu
subtitle: "@kyfuse"
email: "(Private)"
description: I am Kyle Fu, an MIT student looking to better the world through computer science.
url: "https://kylefu.me" # the base hostname & protocol for your site
author: Kyle Fu
street_address: "(Private)"
city: "(Private)"
state: "CA"
zip_code: ""
country: "United States of America"
phone: "(XXX) XXX-XXXX"

# plugins
plugins:
  - jemoji
  - jekyll-sitemap

# collections
collections:
  projects:
    output: true

# https://stackoverflow.com/questions/18675610/jekyll-change-layout-if-page-is-a-post
# default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: post
      is_post: true # automatically set is_post=true for all posts
      description: ""
      image: ""
      imagealt: ""
  -
    scope:
      path: ""
      type: projects
    values:
      layout: post

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/kyfuse
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/kyfuse
  Twitter:
  Facebook:
  Slack:
  YouTube-Play: https://www.youtube.com/@kyfuse

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

# jekyll-admin
jekyll_admin:
  hidden_links:
    - datafiles
    - projects
    - pages
  homepage: "posts"
